
const http=require('http'),https=require('https'),fs=require('fs'),path=require('path'),WebSocket=require('ws');
const PORT=process.env.PORT||3000,DB=(process.env.SUPABASE_URL&&process.env.SUPABASE_URL.includes('.supabase.co'))?process.env.SUPABASE_URL.replace(/\/rest\/v1\/?$/,''): 'https://iffrhyhslqvpzxmxutrk.supabase.co',KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const symbols=['R_10','R_15','R_25','R_30','R_50','R_75','R_100'];
const names={R_10:'Volatility 10 Index',R_15:'Volatility 15 Index',R_25:'Volatility 25 Index',R_30:'Volatility 30 Index',R_50:'Volatility 50 Index',R_75:'Volatility 75 Index',R_100:'Volatility 100 Index'};
function supa(method,pathName,body){return new Promise((resolve,reject)=>{if(!DB||!KEY)return reject(new Error('Supabase variables missing'));let u=new URL(DB+pathName),data=body?JSON.stringify(body):null;let r=https.request({hostname:u.hostname,path:u.pathname+u.search,method,headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json',Prefer:'return=minimal',...(data?{'Content-Length':Buffer.byteLength(data)}:{})}},x=>{let out='';x.on('data',b=>out+=b);x.on('end',()=>resolve({status:x.statusCode,body:out}))});r.on('error',reject);if(data)r.write(data);r.end()})}
async function saveTick(asset,quote,epoch){const q=String(quote),digit=Number(q.replace(/\D/g,'').slice(-1));try{const r=await supa('POST','/rest/v1/tick_history',{asset,quote,digit,tick_time:new Date(epoch*1000).toISOString()});if(r.status<200||r.status>=300)console.log('history save failed',r.status,r.body)}catch(e){console.log('history save failed',e.message)}}
async function getHistory(asset,res){try{const r=await supa('GET','/rest/v1/tick_history?asset=eq.'+encodeURIComponent(asset)+'&order=tick_time.desc&limit=1000');res.writeHead(r.status>=200&&r.status<300?200:500,{'Content-Type':'application/json'});res.end(r.body)}catch(e){res.writeHead(503,{'Content-Type':'application/json'});res.end(JSON.stringify({error:e.message}))}}
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');if(u.pathname==='/history')return getHistory(u.searchParams.get('asset')||'R_10',res);const f=u.pathname==='/'?path.join(__dirname,'public/index.html'):path.join(__dirname,'public',u.pathname);fs.readFile(f,(e,d)=>{if(e){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':f.endsWith('.html')?'text/html':'text/plain'});res.end(d)})});
const wss=new WebSocket.Server({server}),clients=new Set();function send(o){const s=JSON.stringify(o);for(const c of clients)if(c.readyState===1)c.send(s)}
function connect(){const d=new WebSocket('wss://api.derivws.com/trading/v1/options/ws/public');d.on('open',()=>{send({status:'Conectado a Deriv'});symbols.forEach(s=>d.send(JSON.stringify({ticks:s,subscribe:1}))) });d.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return}if(m.errors){send({status:'ERROR Deriv: '+m.errors[0].message});return}if(m.tick){const s=m.tick.symbol;saveTick(s,m.tick.quote,m.tick.epoch);send({status:'TICK RECIBIDO',symbol:s,name:names[s]||s,quote:m.tick.quote,epoch:m.tick.epoch})}});d.on('error',()=>send({status:'ERROR WebSocket'}));d.on('close',()=>{send({status:'Desconectado; reintentando'});setTimeout(connect,3000)})}
wss.on('connection',c=>{clients.add(c);c.send(JSON.stringify({status:'Conectado a Deriv',symbols:names}));c.on('close',()=>clients.delete(c))});connect();server.listen(PORT,()=>console.log('Listening on '+PORT));
